stages:
  - build
  - publish

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint:
      - ""
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  rules:
    - if: $CI_COMMIT_TAG

publish:
  stage: publish
  dependencies:
    - "build"
  needs:
    - "build"
  image: docker:28.1.1
  services:
    - docker:28.1.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    USERNAME: ${DH_USER}
    PASSWORD: ${DH_PASSWORD}
  before_script:
    - docker info
  script:
    - docker login docker.io --username ${USERNAME} --password ${PASSWORD}
    - docker login registry.gitlab.com --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD}
    - docker pull registry.gitlab.com/sv4u/musicdl:${CI_COMMIT_TAG}
    - docker tag registry.gitlab.com/sv4u/musicdl:${CI_COMMIT_TAG} docker.io/sv4u/musicdl:${CI_COMMIT_TAG}
    - docker tag registry.gitlab.com/sv4u/musicdl:${CI_COMMIT_TAG} docker.io/sv4u/musicdl:latest
    - docker push docker.io/sv4u/musicdl:${CI_COMMIT_TAG}
    - docker push docker.io/sv4u/musicdl:latest
  rules:
    - if: $CI_COMMIT_TAG
