stages:
  - build
  - publish

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  USER: ${DH_USERNAME}
  PASSWORD: ${DH_PASSWORD}

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint:
      - ""
  script:
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile ${CI_PROJECT_DIR}/musicdl.Dockerfile
      --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      --destination ${CI_REGISTRY_IMAGE}:latest
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --build-arg PLEX_USERNAME=${PLEX_USERNAME}
      --build-arg PLEX_PASSWORD=${PLEX_PASSWORD}
      --build-arg PLEX_SERVER=${PLEX_SERVER}
      --dockerfile ${CI_PROJECT_DIR}/plex-playlist-push.Dockerfile
      --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-plex-playlist-push
      --destination ${CI_REGISTRY_IMAGE}:latest-plex-playlist-push
  rules:
    - if: $CI_COMMIT_TAG

publish:
  stage: publish
  dependencies:
    - "build"
  needs:
    - "build"
  image: docker:28.1.1
  services:
    - docker:28.1.1-dind
  before_script:
    - docker info
  script:
    - docker login docker.io --username ${USER} --password ${PASSWORD}
    - docker login registry.gitlab.com --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD}
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-plex-playlist-push
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} docker.io/sv4u/musicdl:${CI_COMMIT_TAG}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-plex-playlist-push docker.io/sv4u/musicdl:${CI_COMMIT_TAG}-plex-playlist-push
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} docker.io/sv4u/musicdl:latest
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-plex-playlist-push docker.io/sv4u/plex-playlist-push:latest
    - docker push docker.io/sv4u/musicdl:${CI_COMMIT_TAG}
    - docker push docker.io/sv4u/musicdl:latest
    - docker push docker.io/sv4u/musicdl:${CI_COMMIT_TAG}-plex-playlist-push
    - docker push docker.io/sv4u/musicdl:latest-plex-playlist-push
  rules:
    - if: $CI_COMMIT_TAG
